# FIFA video game players rating prediction

importing libraries will be used

In [9]:
import seaborn as sns
import matplotlib.pyplot as plt
import math

In [10]:

#import pandas as pd
#import numpy as  np 
#from bs4 import BeautifulSoup 
#import requests
#player_dict = {'OVR':,'PAC':,'SHO':,'PAS':,'DRI':,'DEF':,'PHY':,}
#url = requests.get('https://www.ea.com/games/ea-sports-fc/ratings').text 
#soup = BeautifulSoup(url,'html5lib')
#html_tables = soup.find_all('table')
#OVR_list = []

#for x in list(range(1, 6)):
#    first_table = html_tables[x]
#    t = list(first_table.find('tr').stripped_strings)
#    OVR_list.append(t[1])
#OVR_list
    

#attributes_to_extract = ['PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']
#found_data_list = []

#for x in range(1, 6):
#    data_list = list(html_tables[x].find_all('tr')[1].stripped_strings)
#    player_data = {}
#    player_data['OVR']= OVR_list[x-1] 
#    for attribute in attributes_to_extract:
 #       if attribute in data_list:
#            index = data_list.index(attribute)
#            player_data[attribute] = data_list[index + 1]

       
#    found_data_list.append(player_data)


    
#print(found_data_list)

[{'OVR': '91', 'PAC': '97', 'SHO': '90', 'PAS': '80', 'DRI': '92', 'DEF': '36', 'PHY': '78'}, {'OVR': '91', 'PAC': '82', 'SHO': '90', 'PAS': '91', 'DRI': '92', 'DEF': '72', 'PHY': '78'}, {'OVR': '91', 'PAC': '89', 'SHO': '93', 'PAS': '66', 'DRI': '80', 'DEF': '45', 'PHY': '88'}, {'OVR': '91', 'PAC': '72', 'SHO': '88', 'PAS': '94', 'DRI': '87', 'DEF': '65', 'PHY': '78'}, {'OVR': '90', 'PAC': '81', 'SHO': '84', 'PAS': '83', 'DRI': '91', 'DEF': '75', 'PHY': '73'}]

using BeautifulSoup library to extract all the data for the first 100 player from fifa website

In [11]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
import html5lib 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn import metrics
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import Ridge
url = requests.get('https://www.ea.com/games/ea-sports-fc/ratings').text
soup = BeautifulSoup(url, 'html5lib')
html_tables = soup.find_all('table')

names_list = []
Position_list = []
OVR_list = []
PAC_list = []
SHO_list = []
PAS_list = []
DRI_list = []
DEF_list = []
PHY_list = []

def extract_name(x):
    table_1 = html_tables[0].find_all('tr')[x]
    name_cell = table_1.find_all('td')[1].find('a')
    names_list.append(name_cell.text)
    
def extract_position(x):
    table_1 = html_tables[0].find_all('tr')[x]
    position_cell = table_1.find_all('td')[4].find('a')
    Position_list.append(position_cell.text)

def extract_OVR(x):
    table_1 = html_tables[0].find_all('tr')[x]
    OVR_cell = list(table_1.find_all('td')[5].stripped_strings)
    OVR_list.append(OVR_cell[1])

def extract_PAC(x):
    table_1 = html_tables[0].find_all('tr')[x]
    PAC_cell = list(table_1.find_all('td')[6].stripped_strings)
    PAC_list.append(PAC_cell[1])

def extract_SHO(x):
    table_1 = html_tables[0].find_all('tr')[x]
    SHO_cell = list(table_1.find_all('td')[7].stripped_strings)
    SHO_list.append(SHO_cell[1])  

def extract_PAS(x):
    table_1 = html_tables[0].find_all('tr')[x]
    PAS_cell = list(table_1.find_all('td')[8].stripped_strings)
    PAS_list.append(PAS_cell[1])

def extract_DRI(x):
    table_1 = html_tables[0].find_all('tr')[x]
    DRI_cell = list(table_1.find_all('td')[9].stripped_strings)
    DRI_list.append(DRI_cell[1])

def extract_DEF(x):
    table_1 = html_tables[0].find_all('tr')[x]
    DEF_cell = list(table_1.find_all('td')[10].stripped_strings)
    DEF_list.append(DEF_cell[1])

def extract_PHY(x):
    table_1 = html_tables[0].find_all('tr')[x]
    PHY_cell = list(table_1.find_all('td')[11].stripped_strings)
    PHY_list.append(PHY_cell[1])

for x in range(1,400,4):
    extract_name(x)
    extract_position(x)
    extract_OVR(x)
    extract_PAC(x)
    extract_SHO(x)
    extract_PAS(x)
    extract_DRI(x)
    extract_DEF(x)
    extract_PHY(x)


print(names_list)
print(Position_list)
print(OVR_list)
print(PAC_list)
print(SHO_list)
print(PAS_list)
print(DRI_list)
print(DEF_list)
print(PHY_list)

['Kylian Mbappé', 'Alexia Putellas', 'Erling Haaland', 'Kevin De Bruyne', 'Aitana Bonmatí', 'Lionel Messi', 'Sam Kerr', 'Karim Benzema', 'Thibaut Courtois', 'Harry Kane', 'Caroline Graham Hansen', 'Robert Lewandowski', 'Mohamed Salah', 'Kadidiatou Diani', 'Mapi León', 'Rúben Dias', 'Vini Jr.', 'Rodri', 'Neymar Jr', 'Alex Morgan', 'Marc-André ter Stegen', 'Virgil van Dijk', 'Alisson', 'Ada Hegerberg', 'Casemiro', 'Irene Paredes', 'Bruno Fernandes', 'Wendie Renard', 'Antoine Griezmann', 'Victor Osimhen', 'Alexandra Popp', 'Debinha', 'Bernardo Silva', 'Federico Valverde', 'Sophia Smith', 'Ederson', 'Guro Reiten', 'Joshua Kimmich', 'Jan Oblak', 'Christiane Endler', 'Marie Katoto', 'Patri Guijarro', 'Fridolina Rolfö', 'Luka Modrić', 'Lucy Bronze', 'Frenkie de Jong', 'Lautaro Martínez', 'Beth Mead', 'Ewa Pajor', 'Martin Ødegaard', 'Mike Maignan', 'Lena Oberdorf', 'Lina Magull', 'Marquinhos', 'Gregor Kobel', 'Heung Min Son', 'Rose Lavelle', 'Sandra Paños', 'Gianluigi Donnarumma', 'Manuel Neuer', 'Ousmane Dembélé', 'Selma Bacha', 'Mary Earps', 'Bukayo Saka', 'Jude Bellingham', 'Rafael Leão', 'Pedri', 'Lauren Hemp', 'Matthijs de Ligt', 'Sandro Tonali', 'Riyad Mahrez', 'Grace Geyoro', 'Jamal Musiala', 'Nicolò Barella', 'Jill Roord', 'Ronald Araujo', 'Paulo Dybala', 'İlkay Gündoğan', 'Vivianne Miedema', 'Sergej Milinković-Savić', 'Khvicha Kvaratskhelia', 'Andrew Robertson', 'Parejo', 'Sakina Karchaoui', 'Sadio Mané', 'Toni Kroos', 'Lindsey Horan', 'Éder Militão', 'Christopher Nkunku', "N'Golo Kanté", 'Kim Little', 'Lea Schüller', 'João Cancelo', 'Cristiano Ronaldo', 'Trent Alexander-Arnold', 'Ashley Lawrence', 'Mallory Swanson', 'Wojciech Szczęsny', 'Cristiana Girelli', 'Jack Grealish']
['ST', 'CM', 'ST', 'CM', 'CM', 'CF', 'ST', 'CF', 'GK', 'ST', 'RW', 'ST', 'RW', 'RW', 'CB', 'CB', 'LW', 'CDM', 'LW', 'ST', 'GK', 'CB', 'GK', 'ST', 'CDM', 'CB', 'CAM', 'CB', 'ST', 'ST', 'ST', 'CAM', 'CM', 'CM', 'ST', 'GK', 'LW', 'CDM', 'GK', 'GK', 'ST', 'CM', 'LB', 'CM', 'RB', 'CM', 'ST', 'RW', 'ST', 'CAM', 'GK', 'CDM', 'CAM', 'CB', 'GK', 'LW', 'CAM', 'GK', 'GK', 'GK', 'RW', 'LB', 'GK', 'RW', 'CM', 'LW', 'CM', 'LW', 'CB', 'CDM', 'RM', 'CM', 'CAM', 'CM', 'CAM', 'CB', 'CF', 'CM', 'ST', 'CM', 'LW', 'LB', 'CM', 'LB', 'CF', 'CM', 'CM', 'CB', 'CF', 'CDM', 'CM', 'ST', 'LB', 'ST', 'RB', 'RB', 'LW', 'GK', 'ST', 'LW']
['91', '91', '91', '91', '90', '90', '90', '90', '90', '90', '90', '90', '89', '89', '89', '89', '89', '89', '89', '89', '89', '89', '89', '89', '89', '88', '88', '88', '88', '88', '88', '88', '88', '88', '88', '88', '88', '88', '88', '88', '88', '88', '87', '87', '87', '87', '87', '87', '87', '87', '87', '87', '87', '87', '87', '87', '87', '87', '87', '87', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '86', '85']
['97', '82', '89', '72', '81', '80', '85', '79', '85', '69', '89', '75', '89', '89', '75', '62', '95', '58', '86', '83', '86', '78', '86', '75', '63', '69', '71', '53', '80', '90', '73', '84', '69', '88', '93', '86', '88', '70', '85', '87', '83', '78', '82', '72', '73', '82', '80', '81', '85', '72', '85', '58', '81', '78', '86', '87', '86', '86', '90', '84', '93', '87', '83', '85', '76', '93', '78', '90', '66', '84', '79', '77', '85', '78', '77', '79', '80', '62', '82', '68', '84', '80', '49', '89', '85', '51', '78', '85', '82', '69', '76', '86', '81', '77', '76', '86', '93', '86', '81', '76']
['90', '90', '93', '88', '84', '87', '88', '88', '89', '93', '86', '91', '87', '85', '74', '39', '82', '73', '83', '89', '85', '60', '85', '89', '75', '51', '86', '67', '88', '86', '87', '81', '78', '82', '85', '82', '80', '74', '90', '82', '88', '82', '82', '76', '68', '69', '86', '84', '89', '81', '82', '61', '74', '56', '84', '88', '78', '82', '82', '85', '77', '72', '83', '81', '75', '80', '69', '76', '61', '74', '81', '72', '75', '78', '84', '51', '85', '81', '85', '80', '80', '61', '83', '61', '83', '80', '84', '50', '81', '65', '78', '83', '73', '88', '69', '67', '82', '83', '85', '76']
['80', '91', '66', '94', '83', '90', '74', '83', '76', '84', '88', '80', '81', '83', '81', '66', '78', '80', '85', '80', '89', '71', '85', '77', '79', '67', '90', '69', '87', '66', '76', '87', '86', '84', '78', '91', '86', '88', '78', '84', '77', '83', '82', '89', '80', '86', '71', '84', '63', '88', '87', '77', '84', '75', '74', '80', '84', '84', '79', '90', '81', '84', '83', '79', '79', '75', '82', '84', '64', '81', '81', '82', '76', '82', '84', '65', '85', '84', '70', '82', '81', '82', '90', '82', '79', '90', '86', '69', '83', '73', '83', '70', '85', '75', '90', '82', '82', '73', '71', '84']
['92', '92', '80', '87', '91', '94', '90', '87', '93', '83', '90', '87', '88', '88', '76', '69', '90', '80', '93', '88', '91', '72', '89', '86', '73', '68', '83', '69', '88', '83', '82', '91', '92', '84', '88', '86', '86', '84', '87', '90', '84', '86', '87', '87', '80', '87', '85', '87', '89', '87', '89', '76', '86', '74', '89', '84', '87', '89', '89', '84', '87', '82', '85', '87', '85', '87', '88', '87', '68', '81', '89', '82', '91', '85', '85', '62', '90', '86', '86', '82', '87', '81', '80', '87', '87', '81', '84', '71', '88', '80', '88', '81', '84', '80', '79', '80', '84', '87', '81', '88']
['36', '72', '45', '65', '75', '33', '42', '39', '46', '49', '47', '44', '45', '56', '90', '89', '29', '85', '37', '47', '47', '89', '56', '39', '89', '89', '69', '91', '58', '42', '52', '46', '70', '80', '45', '64', '60', '82', '46', '42', '39', '81', '83', '72', '85', '77', '48', '67', '21', '61', '51', '87', '57', '89', '44', '42', '45', '56', '52', '49', '36', '79', '41', '60', '78', '27', '70', '63', '85', '82', '38', '83', '63', '78', '52', '86', '40', '72', '32', '79', '41', '81', '73', '79', '44', '70', '63', '86', '62', '85', '62', '33', '80', '34', '80', '82', '42', '49', '46', '53']
['78', '78', '88', '78', '73', '64', '85', '78', '90', '83', '75', '84', '76', '77', '81', '87', '68', '84', '61', '77', '86', '86', '90', '76', '88', '80', '77', '84', '75', '82', '88', '68', '69', '82', '82', '86', '63', '79', '86', '89', '71', '72', '80', '66', '88', '78', '85', '73', '69', '64', '85', '89', '68', '80', '85', '70', '65', '87', '83', '88', '57', '78', '85', '70', '82', '76', '74', '68', '86', '84', '60', '78', '61', '80', '73', '84', '60', '73', '81', '86', '71', '77', '69', '65', '74', '71', '78', '82', '67', '77', '66', '73', '72', '74', '73', '78', '71', '86', '78', '73']

turn these lists of data to dataframe

In [12]:
Dict_players = {'Name':names_list , 'Position' : Position_list  , "PAC":PAC_list , 'SHO':SHO_list , 'PAS': PAS_list , 'DRI':DRI_list , 'DEF': DEF_list , 'PHY':PHY_list, 'OVR': OVR_list}
df = pd.DataFrame(Dict_players)
df = df.set_index(pd.RangeIndex(start=1, stop=len(df) + 1))
df

                  Name Position PAC SHO PAS DRI DEF PHY OVR
1        Kylian Mbappé       ST  97  90  80  92  36  78  91
2      Alexia Putellas       CM  82  90  91  92  72  78  91
3       Erling Haaland       ST  89  93  66  80  45  88  91
4      Kevin De Bruyne       CM  72  88  94  87  65  78  91
5       Aitana Bonmatí       CM  81  84  83  91  75  73  90
..                 ...      ...  ..  ..  ..  ..  ..  ..  ..
96     Ashley Lawrence       RB  86  67  82  80  82  78  86
97     Mallory Swanson       LW  93  82  82  84  42  71  86
98   Wojciech Szczęsny       GK  86  83  73  87  49  86  86
99   Cristiana Girelli       ST  81  85  71  81  46  78  86
100      Jack Grealish       LW  76  76  84  88  53  73  85

[100 rows x 9 columns]

now have the table for each attribute of the players in details

Pace table

In [13]:
Acceleration = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Acceleration' :
         Acceleration.append(y[1])
Acceleration = Acceleration[0:100] 

SprintSpeed = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Sprint Speed' :
         SprintSpeed.append(y[1])
SprintSpeed = SprintSpeed[0:100]  

Dict_PAC = {'Name':names_list  ,'Position':Position_list, 'Acceleration':Acceleration , 'Sprint Speed': SprintSpeed, "PAC":PAC_list}
dfPAC = pd.DataFrame(Dict_PAC)
dfPAC = dfPAC.set_index(pd.RangeIndex(start=1, stop=len(dfPAC) + 1))
dfPAC.head()

              Name Position Acceleration Sprint Speed PAC
1    Kylian Mbappé       ST           97           97  97
2  Alexia Putellas       CM           81           82  82
3   Erling Haaland       ST           82           94  89
4  Kevin De Bruyne       CM           72           72  72
5   Aitana Bonmatí       CM           82           80  81

Turn position column to numrical for modeling

In [14]:
dfPAC[['Acceleration','Sprint Speed','PAC']] = dfPAC[['Acceleration','Sprint Speed','PAC']].astype(int)
x = pd.get_dummies(dfPAC['Position']).astype(int)
dfPAC1 = pd.concat([dfPAC,x],axis=1)
dfPAC1.drop(columns='Position')
dfPAC1.head()

,Name,Position,Acceleration,Sprint Speed,PAC,CAM,CB,CDM,CF,CM,GK,LB,LW,RB,RM,RW,ST
1,Kylian Mbappé,ST,97,97,97,0,0,0,0,0,0,0,0,0,0,0,1
2,Alexia Putellas,CM,81,82,82,0,0,0,0,1,0,0,0,0,0,0,0
3,Erling Haaland,ST,82,94,89,0,0,0,0,0,0,0,0,0,0,0,1
4,Kevin De Bruyne,CM,72,72,72,0,0,0,0,1,0,0,0,0,0,0,0
5,Aitana Bonmatí,CM,82,80,81,0,0,0,0,1,0,0,0,0,0,0,0

create the model that predict the overall Pace depend on the attributes in the pace section

In [60]:
x_PAC = dfPAC1.drop(columns=['PAC','Name','Position']).values
y_PAC = dfPAC1['PAC'].values
x_PAC = preprocessing.StandardScaler().fit(x_PAC).transform(x_PAC)
x_train_PAC , x_test_PAC, y_train_PAC , y_test_PAC = train_test_split(x_PAC , y_PAC , test_size=0.1, random_state=3)
model_PAC = Ridge(alpha=0.1).fit(x_train_PAC,y_train_PAC)
yhat = model_PAC.predict(x_test_PAC)
mse = mean_squared_error(y_test_PAC,yhat)
accuracy = metrics.r2_score(y_test_PAC,yhat)
print('The mean square error of this model is',mse)
print('The accuracy of this model is',accuracy*100,'%')
yhat_PAC  =model_PAC.predict(x_PAC)
for x in range(0,len(yhat_PAC)-1):
    yhat_PAC[x] = math.ceil(yhat_PAC[x])
yhat_PAC = yhat_PAC.astype(int)

The mean square error of this model is 0.35755108160801524
The accuracy of this model is 99.57855836679866 %

Shooting table

In [16]:
Positioning = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Positioning' :
         Positioning.append(y[1])
Positioning = Positioning[0:100] 


Finishing = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Finishing' :
         Finishing.append(y[1])
Finishing = Finishing[0:100] 

ShotPower = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Shot Power' :
         ShotPower.append(y[1])
ShotPower = ShotPower[0:100]

LongShots = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Long Shots' :
         LongShots.append(y[1])
LongShots = LongShots[0:100] 

Volleys = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Volleys' :
         Volleys.append(y[1])
Volleys = Volleys[0:100]  

Penalties = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Penalties' :
         Penalties.append(y[1])
Penalties = Penalties[0:100] 

Dict_SHO = {'Name':names_list ,'Position':Position_list, 'Positioning': Positioning , 'Finishing':Finishing , 'Shot Power': ShotPower , 'Long Shots':LongShots,'Volleys': Volleys , 'Penalties':Penalties, 'SHO':SHO_list}
dfSHO = pd.DataFrame(Dict_SHO)
dfSHO = dfSHO.set_index(pd.RangeIndex(start=1, stop=len(dfSHO) + 1))
dfSHO.head()

,Name,Position,Positioning,Finishing,Shot Power,Long Shots,Volleys,Penalties,SHO
1,Kylian Mbappé,ST,93,94,90,83,84,84,90
2,Alexia Putellas,CM,91,91,86,89,90,91,90
3,Erling Haaland,ST,96,96,94,86,90,84,93
4,Kevin De Bruyne,CM,88,85,92,92,83,83,88
5,Aitana Bonmatí,CM,91,91,69,89,62,70,84

Turn position column to numrical for modeling

In [17]:
dfSHO[['Positioning','Finishing','Shot Power','Long Shots','Volleys','Penalties','SHO']] = dfSHO[['Positioning','Finishing','Shot Power','Long Shots','Volleys','Penalties','SHO']].astype(int)
x = pd.get_dummies(dfSHO['Position']).astype(int)
dfSHO1 = pd.concat([dfSHO,x],axis=1)
dfSHO1.head()

,Name,Position,Positioning,Finishing,Shot Power,Long Shots,Volleys,Penalties,SHO,CAM,...,CDM,CF,CM,GK,LB,LW,RB,RM,RW,ST
1,Kylian Mbappé,ST,93,94,90,83,84,84,90,0,...,0,0,0,0,0,0,0,0,0,1
2,Alexia Putellas,CM,91,91,86,89,90,91,90,0,...,0,0,1,0,0,0,0,0,0,0
3,Erling Haaland,ST,96,96,94,86,90,84,93,0,...,0,0,0,0,0,0,0,0,0,1
4,Kevin De Bruyne,CM,88,85,92,92,83,83,88,0,...,0,0,1,0,0,0,0,0,0,0
5,Aitana Bonmatí,CM,91,91,69,89,62,70,84,0,...,0,0,1,0,0,0,0,0,0,0

create the model that predict the overall Shooting depend on the attributes in the Shooting section

In [18]:
x_SHO = dfSHO1.drop(columns=['SHO','Name','Position']).values
y_SHO = dfSHO1['SHO'].values
x_SHO = preprocessing.StandardScaler().fit(x_SHO).transform(x_SHO)
x_train_SHO , x_test_SHO , y_train_SHO , y_test_SHO = train_test_split(x_SHO , y_SHO , test_size=0.1, random_state=3)
model_SHO = Ridge(alpha=0.1).fit(x_train_SHO,y_train_SHO)
yhat = model_SHO.predict(x_test_SHO)
mse = mean_squared_error(y_test_SHO,yhat)
accuracy = metrics.r2_score(y_test_SHO,yhat)
print('The mean square error of this model is',mse)
print('The accuracy of this model is',accuracy*100,'%')
yhat_SHO  =model_SHO.predict(x_SHO)
for x in range(0,len(yhat_SHO)-1):
    yhat_SHO[x] = math.ceil(yhat_SHO[x])
yhat_SHO = yhat_SHO.astype(int)

The mean square error of this model is 0.8876129527508692
The accuracy of this model is 99.65220291025004 %

Passing table

In [19]:
Vision = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Vision' :
         Vision.append(y[1])
Vision = Vision[0:100] 

Crossing = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Crossing' :
         Crossing.append(y[1])
Crossing = Crossing[0:100] 

FreeKickAccuracy = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Free Kick Accuracy' :
         FreeKickAccuracy.append(y[1])
FreeKickAccuracy = FreeKickAccuracy[0:100] 

ShortPassing = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Short Passing' :
         ShortPassing.append(y[1])
ShortPassing = ShortPassing[0:100]  

LongPassing = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Long Passing' :
         LongPassing.append(y[1])
LongPassing = LongPassing[0:100] 

Curve = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Curve' :
         Curve.append(y[1])
Curve = Curve[0:100] 

Dict_PAS = {'Name':names_list ,'Position':Position_list, 'Vision': Vision , 'Crossing':Crossing , 'Free Kick Accuracy': FreeKickAccuracy , 'Short Passing':ShortPassing,'Long Passing': LongPassing , 'Curve':Curve , 'PAS':PAS_list}
dfPAS = pd.DataFrame(Dict_PAS)
dfPAS = dfPAS.set_index(pd.RangeIndex(start=1, stop=len(dfPAS) + 1))
dfPAS.head()

,Name,Position,Vision,Crossing,Free Kick Accuracy,Short Passing,Long Passing,Curve,PAS
1,Kylian Mbappé,ST,83,78,69,86,71,80,80
2,Alexia Putellas,CM,91,88,89,94,91,89,91
3,Erling Haaland,ST,74,47,62,77,53,77,66
4,Kevin De Bruyne,CM,95,95,83,94,94,92,94
5,Aitana Bonmatí,CM,90,67,67,91,87,76,83

Turn position column to numrical for modeling

In [20]:
dfPAS[['Vision','Crossing','Free Kick Accuracy','Short Passing','Long Passing','Curve','PAS']] = dfPAS[['Vision','Crossing','Free Kick Accuracy','Short Passing','Long Passing','Curve','PAS']].astype(int)
x = pd.get_dummies(dfPAS['Position']).astype(int)
dfPAS1 = pd.concat([dfPAS,x],axis=1)
dfPAS1.head()

,Name,Position,Vision,Crossing,Free Kick Accuracy,Short Passing,Long Passing,Curve,PAS,CAM,...,CDM,CF,CM,GK,LB,LW,RB,RM,RW,ST
1,Kylian Mbappé,ST,83,78,69,86,71,80,80,0,...,0,0,0,0,0,0,0,0,0,1
2,Alexia Putellas,CM,91,88,89,94,91,89,91,0,...,0,0,1,0,0,0,0,0,0,0
3,Erling Haaland,ST,74,47,62,77,53,77,66,0,...,0,0,0,0,0,0,0,0,0,1
4,Kevin De Bruyne,CM,95,95,83,94,94,92,94,0,...,0,0,1,0,0,0,0,0,0,0
5,Aitana Bonmatí,CM,90,67,67,91,87,76,83,0,...,0,0,1,0,0,0,0,0,0,0

create the model that predict the overall Passing depend on the attributes in the Passing section

In [21]:
x_PAS = dfPAS1.drop(columns=['PAS','Name','Position']).values
y_PAS = dfPAS1['PAS'].values
x_PAS = preprocessing.StandardScaler().fit(x_PAS).transform(x_PAS)
x_train_PAS , x_test_PAS , y_train_PAS , y_test_PAS = train_test_split(x_PAS , y_PAS , test_size=0.05, random_state=22)
model_PAS = Ridge(alpha=0.1).fit(x_train_PAS,y_train_PAS)
yhat = model_PAS.predict(x_test_PAS)
mse = mean_squared_error(y_test_PAS,yhat)
accuracy = metrics.r2_score(y_test_PAS,yhat)
print('The mean square error of this model is',mse)
print('The accuracy of this model is',accuracy*100,'%')
yhat_PAS  =model_PAS.predict(x_PAS)
for x in range(0,len(yhat_PAS)-1):
    yhat_PAS[x] = math.ceil(yhat_PAS[x])
yhat_PAS = yhat_PAS.astype(int)

The mean square error of this model is 0.18260675770142845
The accuracy of this model is 99.7721971585561 %

Dribbling table

In [22]:
Agility = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Agility' :
         Agility.append(y[1])
Agility = Agility[0:100]

Balance = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Balance' :
         Balance.append(y[1])
Balance = Balance[0:100] 

Reactions = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Reactions' :
         Reactions.append(y[1])
Reactions = Reactions[0:100]  

BallControl = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Ball Control' :
         BallControl.append(y[1])
BallControl = BallControl[0:100] 


Dribbling_ = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Dribbling' :
         Dribbling_.append(y[1])
#we made the next step because there are two 'Dribbling' in each player and i want only to read one that is the detailed one                    
Dribbling = Dribbling_[1:200:2]
Dribbling = Dribbling[0:100]

Composure = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Composure' :
         Composure.append(y[1])
Composure = Composure[0:100] 

Dict_DRI = {'Name':names_list  ,'Position':Position_list, 'Agility': Agility , 'Balance':Balance , 'Reactions': Reactions , 'Ball Control':BallControl,'Dribbling': Dribbling , 'Composure':Composure, 'DRI':DRI_list}
dfDRI = pd.DataFrame(Dict_DRI)
dfDRI = dfDRI.set_index(pd.RangeIndex(start=1, stop=len(dfDRI) + 1))
dfDRI.head()

,Name,Position,Agility,Balance,Reactions,Ball Control,Dribbling,Composure,DRI
1,Kylian Mbappé,ST,93,82,93,92,93,88,92
2,Alexia Putellas,CM,90,89,92,94,92,92,92
3,Erling Haaland,ST,76,72,94,82,79,87,80
4,Kevin De Bruyne,CM,74,78,92,92,86,88,87
5,Aitana Bonmatí,CM,93,86,91,91,91,85,91

Turn position column to numrical for modeling

In [23]:
dfDRI[['Agility','Balance','Reactions','Ball Control','Dribbling','Composure','DRI']] = dfDRI[['Agility','Balance','Reactions','Ball Control','Dribbling','Composure','DRI']].astype(int)
x = pd.get_dummies(dfDRI['Position']).astype(int)
dfDRI1 = pd.concat([dfDRI,x],axis=1)
dfDRI1.head()

,Name,Position,Agility,Balance,Reactions,Ball Control,Dribbling,Composure,DRI,CAM,...,CDM,CF,CM,GK,LB,LW,RB,RM,RW,ST
1,Kylian Mbappé,ST,93,82,93,92,93,88,92,0,...,0,0,0,0,0,0,0,0,0,1
2,Alexia Putellas,CM,90,89,92,94,92,92,92,0,...,0,0,1,0,0,0,0,0,0,0
3,Erling Haaland,ST,76,72,94,82,79,87,80,0,...,0,0,0,0,0,0,0,0,0,1
4,Kevin De Bruyne,CM,74,78,92,92,86,88,87,0,...,0,0,1,0,0,0,0,0,0,0
5,Aitana Bonmatí,CM,93,86,91,91,91,85,91,0,...,0,0,1,0,0,0,0,0,0,0

create the model that predict the overall Dribbling depend on the attributes in the Dribbling section

In [24]:
x_DRI = dfDRI1.drop(columns=['DRI','Name','Position']).values
y_DRI = dfDRI1['DRI'].values
x_DRI = preprocessing.StandardScaler().fit(x_DRI).transform(x_DRI)
x_train_DRI , x_test_DRI , y_train_DRI , y_test_DRI = train_test_split(x_DRI , y_DRI , test_size=0.02, random_state=55)
model_DRI = Ridge(alpha=0.1).fit(x_train_DRI,y_train_DRI)
yhat = model_DRI.predict(x_test_DRI)
mse = mean_squared_error(y_test_DRI,yhat)
accuracy = metrics.r2_score(y_test_DRI,yhat)
print('The mean square error of this model is',mse)
print('The accuracy of this model is',accuracy*100,'%')
yhat_DRI  =model_DRI.predict(x_DRI)
for x in range(0,len(yhat_DRI)-1):
    yhat_DRI[x] = math.ceil(yhat_DRI[x])
yhat_DRI = yhat_DRI.astype(int)

The mean square error of this model is 0.029589200728291402
The accuracy of this model is 99.26026998179272 %

Defending table

In [25]:
Interceptions = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Interceptions' :
         Interceptions.append(y[1])
Interceptions = Interceptions[0:100] 


HeadingAccuracy = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Heading Accuracy' :
         HeadingAccuracy.append(y[1])
HeadingAccuracy = HeadingAccuracy[0:100] 

DefAwareness = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Def Awareness' :
         DefAwareness.append(y[1])
DefAwareness = DefAwareness[0:100] 


StandingTackle = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Standing Tackle' :
         StandingTackle.append(y[1])
StandingTackle = StandingTackle[0:100] 


SlidingTackle = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Sliding Tackle' :
         SlidingTackle.append(y[1])
SlidingTackle = SlidingTackle[0:100] 

Dict_DEF = {'Name':names_list ,'Position':Position_list, 'Interceptions': Interceptions , 'Heading Accuracy':HeadingAccuracy , 'Def Awareness': DefAwareness , 'Standing Tackle':StandingTackle,'Sliding Tackle': SlidingTackle, 'DEF':DEF_list }
dfDEF = pd.DataFrame(Dict_DEF)
dfDEF = dfDEF.set_index(pd.RangeIndex(start=1, stop=len(dfDEF) + 1))
dfDEF.head()

,Name,Position,Interceptions,Heading Accuracy,Def Awareness,Standing Tackle,Sliding Tackle,DEF
1,Kylian Mbappé,ST,38,73,26,34,32,36
2,Alexia Putellas,CM,78,74,60,81,64,72
3,Erling Haaland,ST,43,83,38,47,29,45
4,Kevin De Bruyne,CM,66,55,66,70,53,65
5,Aitana Bonmatí,CM,88,54,70,81,67,75

Turn position column to numrical for modeling

In [26]:
dfDEF[['Interceptions','Heading Accuracy','Def Awareness','Standing Tackle','Sliding Tackle','DEF']] = dfDEF[['Interceptions','Heading Accuracy','Def Awareness','Standing Tackle','Sliding Tackle','DEF']].astype(int)
x = pd.get_dummies(dfDEF['Position']).astype(int)
dfDEF1 = pd.concat([dfDEF,x],axis=1)
dfDEF1.head()

,Name,Position,Interceptions,Heading Accuracy,Def Awareness,Standing Tackle,Sliding Tackle,DEF,CAM,CB,CDM,CF,CM,GK,LB,LW,RB,RM,RW,ST
1,Kylian Mbappé,ST,38,73,26,34,32,36,0,0,0,0,0,0,0,0,0,0,0,1
2,Alexia Putellas,CM,78,74,60,81,64,72,0,0,0,0,1,0,0,0,0,0,0,0
3,Erling Haaland,ST,43,83,38,47,29,45,0,0,0,0,0,0,0,0,0,0,0,1
4,Kevin De Bruyne,CM,66,55,66,70,53,65,0,0,0,0,1,0,0,0,0,0,0,0
5,Aitana Bonmatí,CM,88,54,70,81,67,75,0,0,0,0,1,0,0,0,0,0,0,0

create the model that predict the overall Defending depend on the attributes in the Defending section

In [27]:
x_DEF = dfDEF1.drop(columns=['DEF','Name','Position']).values
y_DEF = dfDEF1['DEF'].values
x_DEF = preprocessing.StandardScaler().fit(x_DEF).transform(x_DEF)
x_train_DEF , x_test_DEF , y_train_DEF , y_test_DEF = train_test_split(x_DEF , y_DEF , test_size=0.1, random_state=3)
model_DEF = Ridge(alpha=0.1).fit(x_train_DEF,y_train_DEF)
yhat = model_DEF.predict(x_test_DEF)
mse = mean_squared_error(y_test_DEF,yhat)
accuracy = metrics.r2_score(y_test_DEF,yhat)
print('The mean square error of this model is',mse)
print('The accuracy of this model is',accuracy*100,'%')
yhat_DEF  =model_DEF.predict(x_DEF)
for x in range(0,len(yhat_DEF)-1):
    yhat_DEF[x] = math.ceil(yhat_DEF[x])
yhat_DEF = yhat_DEF.astype(int)

The mean square error of this model is 0.1600225344030654
The accuracy of this model is 99.96210241932431 %

Physical table

In [28]:
Jumping = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Jumping' :
         Jumping.append(y[1])
Jumping = Jumping[0:100]

Stamina = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Stamina' :
         Stamina.append(y[1])
Stamina = Stamina[0:100] 


Strength = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Strength' :
         Strength.append(y[1])
Strength = Strength[0:100] 


Aggression = []
for row in html_tables[0].find_all('tr')[4:]:
    table_1 = row.find('td').find_all('div')
    for x in range(len(table_1)):
        y = list(table_1[x].stripped_strings)
        if y and y[0] == 'Aggression' :
         Aggression.append(y[1])
Aggression = Aggression[0:100] 

Dict_PHY = {'Name':names_list ,'Position':Position_list, 'Jumping': Jumping , 'Stamina':Stamina , 'Strength': Strength , 'Aggression': Aggression , 'PHY':PHY_list }
dfPHY = pd.DataFrame(Dict_PHY)
dfPHY = dfPHY.set_index(pd.RangeIndex(start=1, stop=len(dfPHY) + 1))
dfPHY.head()

              Name Position Jumping Stamina Strength Aggression PHY
1    Kylian Mbappé       ST      88      88       77         64  78
2  Alexia Putellas       CM      84      85       78         70  78
3   Erling Haaland       ST      93      76       93         87  88
4  Kevin De Bruyne       CM      72      88       74         75  78
5   Aitana Bonmatí       CM      75      80       75         60  73

Turn position column to numrical for modeling

In [29]:
dfPHY[['Jumping','Stamina','Strength','Aggression','PHY']] = dfPHY[['Jumping','Stamina','Strength','Aggression','PHY']].astype(int)
x = pd.get_dummies(dfPHY['Position']).astype(int)
dfPHY1 = pd.concat([dfPHY,x],axis=1)
dfPHY1.head()

,Name,Position,Jumping,Stamina,Strength,Aggression,PHY,CAM,CB,CDM,CF,CM,GK,LB,LW,RB,RM,RW,ST
1,Kylian Mbappé,ST,88,88,77,64,78,0,0,0,0,0,0,0,0,0,0,0,1
2,Alexia Putellas,CM,84,85,78,70,78,0,0,0,0,1,0,0,0,0,0,0,0
3,Erling Haaland,ST,93,76,93,87,88,0,0,0,0,0,0,0,0,0,0,0,1
4,Kevin De Bruyne,CM,72,88,74,75,78,0,0,0,0,1,0,0,0,0,0,0,0
5,Aitana Bonmatí,CM,75,80,75,60,73,0,0,0,0,1,0,0,0,0,0,0,0

create the model that predict the overall Physical depend on the attributes in the Physical section

In [30]:
x_PHY = dfPHY1.drop(columns=['PHY','Name','Position']).values
y_PHY = dfPHY1['PHY'].values
x_PHY = preprocessing.StandardScaler().fit(x_PHY).transform(x_PHY)
x_train_PHY , x_test_PHY , y_train_PHY , y_test_PHY = train_test_split(x_PHY , y_PHY , test_size=0.03, random_state=6)
model_PHY = Ridge(alpha=0.1).fit(x_train_PHY,y_train_PHY)
yhat = model_PHY.predict(x_test_PHY)
mse = mean_squared_error(y_test_PHY,yhat)
accuracy = metrics.r2_score(y_test_PHY,yhat)
print('The mean square error of this model is',mse)
print('The accuracy of this model is',accuracy*100,'%')
yhat_PHY  =model_PHY.predict(x_PHY)
for x in range(0,len(yhat_PHY)-1):
    yhat_PHY[x] = math.ceil(yhat_PHY[x])
yhat_PHY = yhat_PHY.astype(int)

The mean square error of this model is 0.009087468805965806
The accuracy of this model is 99.85395139418983 %

Turn position column to numrical for modeling

In [31]:
df[['PAC','SHO','PAS','DRI','DEF','PHY','OVR']] = df[['PAC','SHO','PAS','DRI','DEF','PHY','OVR']].astype(int)
x = pd.get_dummies(df['Position']).astype(int)
df1 = pd.concat([df,x],axis=1)
df1.head()

,Name,Position,PAC,SHO,PAS,DRI,DEF,PHY,OVR,CAM,...,CDM,CF,CM,GK,LB,LW,RB,RM,RW,ST
1,Kylian Mbappé,ST,97,90,80,92,36,78,91,0,...,0,0,0,0,0,0,0,0,0,1
2,Alexia Putellas,CM,82,90,91,92,72,78,91,0,...,0,0,1,0,0,0,0,0,0,0
3,Erling Haaland,ST,89,93,66,80,45,88,91,0,...,0,0,0,0,0,0,0,0,0,1
4,Kevin De Bruyne,CM,72,88,94,87,65,78,91,0,...,0,0,1,0,0,0,0,0,0,0
5,Aitana Bonmatí,CM,81,84,83,91,75,73,90,0,...,0,0,1,0,0,0,0,0,0,0

create the model that predict the overall Rating

In [59]:
x_OVR = df1.drop(columns=['OVR','Name','Position']).values
y_OVR = df1['OVR'].values
x_OVR = preprocessing.StandardScaler().fit(x_OVR).transform(x_OVR)
listt = []
max_index  = 0
for z in range(1,5000):
    x_train_OVR , x_test_OVR , y_train_OVR , y_test_OVR = train_test_split(x_OVR ,y_OVR , test_size=0.02, random_state=z)
    model_OVR = Ridge(alpha=0.1).fit(x_train_OVR,y_train_OVR)
    yhat = model_OVR.predict(x_test_OVR)
    mse = mean_squared_error(y_test_OVR,yhat)
    accuracy = metrics.r2_score(y_test_OVR,yhat)
    listt.append(accuracy*100)
    t = max(listt)
    if t == 99.79987301813237 :
        max_index = z 
          
max(listt) , max_index
print('The accurace of this model is',max(listt),'%')

The accurace of this model is 99.79987301813237 %

There is the predicted attributes except the overall rating for each player

In [34]:
Predicted_Table_dict = {'Name':names_list , 'Position' : Position_list  , "PAC":yhat_PAC , 'SHO':yhat_SHO , 'PAS': yhat_PAS , 'DRI':yhat_DRI , 'DEF': yhat_DEF , 'PHY':yhat_PHY}
Predicted_Table = pd.DataFrame(Predicted_Table_dict)
Predicted_Table = Predicted_Table.set_index(pd.RangeIndex(start=1, stop=len(df) + 1))
x = pd.get_dummies(Predicted_Table['Position']).astype(int)
Predicted_Table1 = pd.concat([Predicted_Table,x],axis=1)
Predicted_Table1.head(10)

,Name,Position,PAC,SHO,PAS,DRI,DEF,PHY,CAM,CB,CDM,CF,CM,GK,LB,LW,RB,RM,RW,ST
1,Kylian Mbappé,ST,96,90,80,91,36,78,0,0,0,0,0,0,0,0,0,0,0,1
2,Alexia Putellas,CM,81,89,91,91,73,78,0,0,0,0,1,0,0,0,0,0,0,0
3,Erling Haaland,ST,89,93,66,84,46,86,0,0,0,0,0,0,0,0,0,0,0,1
4,Kevin De Bruyne,CM,73,88,94,86,66,77,0,0,0,0,1,0,0,0,0,0,0,0
5,Aitana Bonmatí,CM,81,84,83,91,76,74,0,0,0,0,1,0,0,0,0,0,0,0
6,Lionel Messi,CF,81,88,90,93,33,65,0,0,0,1,0,0,0,0,0,0,0,0
7,Sam Kerr,ST,85,90,76,89,43,84,0,0,0,0,0,0,0,0,0,0,0,1
8,Karim Benzema,CF,80,88,82,87,40,77,0,0,0,1,0,0,0,0,0,0,0,0
9,Thibaut Courtois,GK,85,85,78,89,50,85,0,0,0,0,0,1,0,0,0,0,0,0
10,Harry Kane,ST,71,93,84,83,49,83,0,0,0,0,0,0,0,0,0,0,0,1

here we got all the predicted attributes we had predicted to the overall rating model to have the predicted rating for each player

In [35]:
x_ovr = Predicted_Table1.drop(columns=['Name','Position']).values
x_ovr = preprocessing.StandardScaler().fit(x_ovr).transform(x_ovr)
yhat_ovr = model_OVR.predict(x_ovr)
for x in range(0,len(yhat_ovr)-1):
    yhat_ovr[x] = math.ceil(yhat_ovr[x])
yhat_ovr = yhat_ovr.astype(int)

The final predicted table compared with the table that has the actual values

In [36]:
Predicted_Table['OVR'] = yhat_ovr
Predicted_Table.head(10)

                Name Position  PAC  SHO  PAS  DRI  DEF  PHY  OVR
1      Kylian Mbappé       ST   96   90   80   91   36   78   90
2    Alexia Putellas       CM   81   89   91   91   73   78   90
3     Erling Haaland       ST   89   93   66   84   46   86   89
4    Kevin De Bruyne       CM   73   88   94   86   66   77   89
5     Aitana Bonmatí       CM   81   84   83   91   76   74   89
6       Lionel Messi       CF   81   88   90   93   33   65   89
7           Sam Kerr       ST   85   90   76   89   43   84   90
8      Karim Benzema       CF   80   88   82   87   40   77   88
9   Thibaut Courtois       GK   85   85   78   89   50   85   88
10        Harry Kane       ST   71   93   84   83   49   83   90

In [62]:
df.head(10)

                Name Position  PAC  SHO  PAS  DRI  DEF  PHY  OVR
1      Kylian Mbappé       ST   97   90   80   92   36   78   91
2    Alexia Putellas       CM   82   90   91   92   72   78   91
3     Erling Haaland       ST   89   93   66   80   45   88   91
4    Kevin De Bruyne       CM   72   88   94   87   65   78   91
5     Aitana Bonmatí       CM   81   84   83   91   75   73   90
6       Lionel Messi       CF   80   87   90   94   33   64   90
7           Sam Kerr       ST   85   88   74   90   42   85   90
8      Karim Benzema       CF   79   88   83   87   39   78   90
9   Thibaut Courtois       GK   85   89   76   93   46   90   90
10        Harry Kane       ST   69   93   84   83   49   83   90

The next functions used To have the rating of a new player

In [37]:
def predict_new_player_PAC (Name,Position,Acceleration,SprintSpeed):
    q = dfPAC
    q.loc[dfPAC.shape[0]] = {'Name': Name,
 'Position': Position,
 'Acceleration': Acceleration,
 'Sprint Speed': SprintSpeed,
 'PAC': 0,
   }
    x = pd.get_dummies(q['Position']).astype(int)
    q = pd.concat([q,x],axis=1)
    o = q.drop(columns=['Name','Position','PAC']).values
    o = preprocessing.StandardScaler().fit(o).transform(o)
    o = [o[99]]
    
    g = model_PAC.predict(o).astype(int)
    q['PAC'][100] = g
    dfPAC['PAC'][100] = g
    return (g)

def predict_new_player_SHO (Name,Position,POSITIONING,FINISHING,SHOTPOWER,LONGSHOTS,VOLLEYS,PENALTIES):
    q = dfSHO
    q.loc[dfSHO.shape[0]] = {'Name': Name,
 'Position': Position,
 'Positioning': POSITIONING,
 'Finishing': FINISHING,
 'Shot Power':SHOTPOWER,
 'Long Shots':LONGSHOTS,
 'Volleys':VOLLEYS,
 'Penalties':PENALTIES,
 'SHO': 0,
   }
    x = pd.get_dummies(q['Position']).astype(int)
    q = pd.concat([q,x],axis=1)
    o = q.drop(columns=['Name','Position','SHO']).values
    o = preprocessing.StandardScaler().fit(o).transform(o)
    o = [o[99]]
    
    g = model_SHO.predict(o).astype(int)
    q['SHO'][100] = g
    dfSHO['SHO'][100] = g
    return (g)

def predict_new_player_PAS (Name,Position,Vision,Crossing,FreeKickAccuracy,ShortPassing,LongPassing,Curve):
    q = dfPAS
    q.loc[dfPAS.shape[0]] = {'Name': Name,
 'Position': Position,
 'Vision': Vision,
 'Crossing': Crossing,
 'Free Kick Accuracy':FreeKickAccuracy,
 'Short Passing':ShortPassing,
 'Long Passing':LongPassing,
 'Curve':Curve,
 'PAS': 0,
   }
    x = pd.get_dummies(q['Position']).astype(int)
    q = pd.concat([q,x],axis=1)
    o = q.drop(columns=['Name','Position','PAS']).values
    o = preprocessing.StandardScaler().fit(o).transform(o)
    o = [o[99]]
    
    g = model_PAS.predict(o).astype(int)
    q['PAS'][100] = g
    dfPAS['PAS'][100] = g
    return (g)



def predict_new_player_DRI (Name,Position,Agility,Balance,Reactions,BallControl,Dribbling,Composure):
    q = dfDRI
    q.loc[dfDRI.shape[0]] = {'Name': Name,
 'Position':Position,
 'Agility': Agility,
 'Balance': Balance,
 'Reactions': Reactions,
 'Ball Control':BallControl,
 'Dribbling':Dribbling,
 'Composure':Composure,
 'DRI': 0,
   }
    x = pd.get_dummies(q['Position']).astype(int)
    q = pd.concat([q,x],axis=1)
    o = q.drop(columns=['Name','Position','DRI']).values
    o = preprocessing.StandardScaler().fit(o).transform(o)
    o = [o[99]]
    
    g = model_DRI.predict(o).astype(int)
    q['DRI'][100] = g
    dfDRI['DRI'][100] = g
    return (g)


def predict_new_player_DEF (Name,Position,Interceptions,HeadingAccuracy,DefAwareness,StandingTackle,SlidingTackle):
    q = dfDEF
    q.loc[dfDEF.shape[0]] = {'Name': Name,
 'Position':Position,
 'Interceptions':Interceptions,
 'Heading Accuracy': HeadingAccuracy,
 'Def Awareness': DefAwareness,
 'Standing Tackle': StandingTackle,
 'Sliding Tackle':SlidingTackle,
 'DEF': 0,
   }
    x = pd.get_dummies(q['Position']).astype(int)
    q = pd.concat([q,x],axis=1)
    o = q.drop(columns=['Name','Position','DEF']).values
    o = preprocessing.StandardScaler().fit(o).transform(o)
    o = [o[99]]
    
    g = model_DEF.predict(o).astype(int)
    q['DEF'][100] = g
    dfDEF['DEF'][100] = g    
    return (g)


def predict_new_player_PHY (Name,Position,Jumping,Stamina,Strength,Aggression):
    q = dfPHY
    q.loc[dfPHY.shape[0]] = {'Name': Name,
 'Position':Position,
 'Jumping': Jumping,
 'Stamina': Stamina,
 'Strength': Strength,
 'Aggression':Aggression,
 'PHY': 0,
   }
    x = pd.get_dummies(q['Position']).astype(int)
    q = pd.concat([q,x],axis=1)
    o = q.drop(columns=['Name','Position','PHY']).values
    o = preprocessing.StandardScaler().fit(o).transform(o)
    o = [o[99]]
    
    g = model_PHY.predict(o).astype(int)
    q['PHY'][100] = g
    dfPHY['PHY'][100] = g    
    return (g)

#def predict_rating_of_player(Name,Position,PAC,SHO,PAS,DRI,DEF,PHY):
#    q = df
#    q.loc[df.shape[0]] = {'Name': Name,
# 'Position':Position,
# 'PAC': PAC,
# 'SHO': SHO,
# 'PAS': PAS,
# 'DRI':DRI,
# 'DEF':DEF,
# 'PHY':PHY,
# 'OVR': 0,
#   }
#    x = pd.get_dummies(q['Position']).astype(int)
#    q = pd.concat([q,x],axis=1)
#    o = q.drop(columns=['Name','Position','OVR']).values
#    o = preprocessing.StandardScaler().fit(o).transform(o)
#    o = [o[99]]
#    
 #   g = model_OVR.predict(o).astype(int)
 #   q['OVR'][100] = g
 #   df['OVR'][100] = g    
 #   return (g)

def rating (Name,Position):
    q = df
    q['Name'].loc[q.shape[0]] == Name
    q['Position'].loc[q.shape[0]] == Position
    x = pd.get_dummies(q['Position']).astype(int)
    q = pd.concat([q,x],axis=1)
    q['PAC'].loc[q.shape[0]] = dfPAC['PAC'].loc[dfPAC.shape[0]]
    q['SHO'].loc[q.shape[0]] = dfSHO['SHO'].loc[dfSHO.shape[0]]
    q['PAS'].loc[q.shape[0]] = dfPAS['PAS'].loc[dfPAS.shape[0]]
    q['DRI'].loc[q.shape[0]] = dfDRI['DRI'].loc[dfDRI.shape[0]]
    q['DEF'].loc[q.shape[0]] = dfDEF['DEF'].loc[dfDEF.shape[0]]
    q['PHY'].loc[q.shape[0]] = dfPHY['PHY'].loc[dfPHY.shape[0]]    
    o = q.drop(columns=['Name','Position','OVR']).values
    o = preprocessing.StandardScaler().fit(o).transform(o)
    o = [o[99]] 
    g = model_OVR.predict(o).astype(int)
    q['OVR'][100] = g
    df['OVR'][100] = g    
    return (g)

Predicting players outside the table of the first 100 players

In [57]:
#here we give the function the detailed attributes and it predict the main ones then the overall rating
print('The predicted PACE for Insigne is',predict_new_player_PAC('Insigne','LW',84,77),'And the actual value is 80')
print('The predicted SHOTTING for Insigne is',predict_new_player_SHO('Insigne','LW',78,77,79,82,76,77),'And the actual value is 78')
print('The predicted PASSING for Insigne is',predict_new_player_PAS('Insigne','LW',83,77,84,80,83,89),'And the actual value is 81')
print('The predicted DRIBBLING for Insigne is',predict_new_player_DRI('Insigne','LW',89,93,75,86,86,81),'And the actual value is 86')
print('The predicted DEFENDING for Insigne is',predict_new_player_DEF('Insigne','LW',26,59,53,24,22),'And the actual value is 36')
print('The predicted PHYSICAL for Insigne is',predict_new_player_PHY('Insigne','LW',61,70,34,34),'And the actual value is 44')
print('The predicted TOTAL OVERALL for Insigne is',rating('Insigne','LW'),'And the actual value is 81')

The predicted PACE for Insigne is [80] And the actual value is 80
The predicted SHOTTING for Insigne is [78] And the actual value is 78
The predicted PASSING for Insigne is [82] And the actual value is 81
The predicted DRIBBLING for Insigne is [86] And the actual value is 86
The predicted DEFENDING for Insigne is [36] And the actual value is 36
The predicted PHYSICAL for Insigne is [50] And the actual value is 44
The predicted TOTAL OVERALL for Insigne is [84] And the actual value is 81

C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['PAC'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfPAC['PAC'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['SHO'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfSHO['SHO'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['PAS'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfPAS['PAS'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['DRI'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfDRI['DRI'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['DEF'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfDEF['DEF'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:132: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['PHY'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfPHY['PHY'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:165: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['PAC'].loc[q.shape[0]] = dfPAC['PAC'].loc[dfPAC.shape[0]]
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:166: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['SHO'].loc[q.shape[0]] = dfSHO['SHO'].loc[dfSHO.shape[0]]
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:167: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['PAS'].loc[q.shape[0]] = dfPAS['PAS'].loc[dfPAS.shape[0]]
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:168: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['DRI'].loc[q.shape[0]] = dfDRI['DRI'].loc[dfDRI.shape[0]]
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:169: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['DEF'].loc[q.shape[0]] = dfDEF['DEF'].loc[dfDEF.shape[0]]
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['PHY'].loc[q.shape[0]] = dfPHY['PHY'].loc[dfPHY.shape[0]]
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:175: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['OVR'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:176: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['OVR'][100] = g

In [58]:
print('The predicted PACE for Konate is',predict_new_player_PAC('Konate','CB',67,85),'And the actual value is 77')
print('The predicted SHOTTING for Konate is',predict_new_player_SHO('Konate','CB',37,29,45,31,28,41),'And the actual value is 34')
print('The predicted PASSING for Konate is',predict_new_player_PAS('Konate','CB',51,38,27,75,69,32),'And the actual value is 57')
print('The predicted DRIBBLING for Konate is',predict_new_player_DRI('Konate','CB',60,52,78,70,68,76),'And the actual value is 68')
print('The predicted DEFENDING for Konate is',predict_new_player_DEF('Konate','CB',81,78,80,85,81),'And the actual value is 82')
print('The predicted PHYSICAL for Konate is',predict_new_player_PHY('Konate','CB',81,65,90,82),'And the actual value is 82')
print('The predicted TOTAL OVERALL for Konate is',rating('Konate','CB'),'And the actual value is 81')

The predicted PACE for Konate is [76] And the actual value is 77
The predicted SHOTTING for Konate is [37] And the actual value is 34
The predicted PASSING for Konate is [57] And the actual value is 57
The predicted DRIBBLING for Konate is [70] And the actual value is 68
The predicted DEFENDING for Konate is [81] And the actual value is 82
The predicted PHYSICAL for Konate is [81] And the actual value is 82
The predicted TOTAL OVERALL for Konate is [79] And the actual value is 81

C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['PAC'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfPAC['PAC'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['SHO'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfSHO['SHO'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['PAS'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfPAS['PAS'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['DRI'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfDRI['DRI'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['DEF'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfDEF['DEF'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:132: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['PHY'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfPHY['PHY'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:165: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['PAC'].loc[q.shape[0]] = dfPAC['PAC'].loc[dfPAC.shape[0]]
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:166: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['SHO'].loc[q.shape[0]] = dfSHO['SHO'].loc[dfSHO.shape[0]]
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:167: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['PAS'].loc[q.shape[0]] = dfPAS['PAS'].loc[dfPAS.shape[0]]
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:168: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['DRI'].loc[q.shape[0]] = dfDRI['DRI'].loc[dfDRI.shape[0]]
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:169: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['DEF'].loc[q.shape[0]] = dfDEF['DEF'].loc[dfDEF.shape[0]]
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['PHY'].loc[q.shape[0]] = dfPHY['PHY'].loc[dfPHY.shape[0]]
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:175: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q['OVR'][100] = g
C:\Users\abdalrhman khaled\AppData\Local\Temp\ipykernel_23112\2365095271.py:176: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['OVR'][100] = g